/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan_1;

import Dao.LichThiDauDao;
import Entities.Lichthidau;
import Helper.DataValidator;
import Helper.MessageDialogHelper;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ltdManagementPanel extends javax.swing.JPanel {
private qlct parentForm;
private DefaultTableModel tblModel;
    /**
     * Creates new form ltdManagementPanel
     */
    public ltdManagementPanel() {
        initComponents();
        initTable();    
        loadDataToTable();
    }
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã trận ","Trận đấu","Ngày","Giờ","Svd"});
        tblCalendar.setModel(tblModel);
    }
    private void loadDataToTable(){
        try {
            LichThiDauDao dao = new LichThiDauDao();
            List <Lichthidau> list = dao.findAllLichThiDau();
            tblModel.setRowCount(0);
            for(Lichthidau lt : list){
                tblModel.addRow(new Object[]{
                   lt.getMatran(),lt.getTrandau(),lt.getNgay(),lt.getGio(),lt.getSVD()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMatranTK = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMatran = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTran = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSVD = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCalendar = new javax.swing.JTable();
        btnTaomoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(1058, 562));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("LỊCH THI ĐẤU");

        jSeparator1.setPreferredSize(new java.awt.Dimension(1018, 475));

        jLabel2.setText("Mã trận");

        txtMatranTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatranTKActionPerformed(evt);
            }
        });

        btnTimkiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMatranTK, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnTimkiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMatranTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem))
                .addGap(161, 161, 161))
        );

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calendar (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Mã Trận");

        txtMatran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatranFocusLost(evt);
            }
        });
        txtMatran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatranActionPerformed(evt);
            }
        });

        jLabel4.setText("Trận");

        jLabel5.setText("Ngày");

        txtNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayActionPerformed(evt);
            }
        });

        jLabel6.setText("Giờ");

        jLabel7.setText("SVĐ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSVD, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(34, 34, 34)
                        .addComponent(txtGio))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTran)
                            .addComponent(txtMatran, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addComponent(txtNgay)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMatran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        tblCalendar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã trận", "Trận đấu", "Ngày", "Giờ", "SVĐ"
            }
        ));
        tblCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCalendarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCalendar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnTaomoi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTaomoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/creation.png"))); // NOI18N
        btnTaomoi.setText("Tạo mới");
        btnTaomoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaomoiActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/diskette.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete (1).png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapnhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCapnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/recycle.png"))); // NOI18N
        btnCapnhat.setText("Cập nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTaomoi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLuu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnXoa)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaomoi)
                    .addComponent(btnLuu)
                    .addComponent(btnXoa)
                    .addComponent(btnCapnhat))
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatranTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatranTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatranTKActionPerformed

    private void txtNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayActionPerformed

    private void txtMatranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatranActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
       try {
           LichThiDauDao dao = new LichThiDauDao();
           Lichthidau lt = dao.findByMaTran(txtMatranTK.getText());
           
           if(lt != null){
              txtMatran.setText(lt.getMatran());
              txtTran.setText(lt.getTrandau());
              txtNgay.setText(lt.getNgay());
              txtGio.setText(lt.getGio());
              txtSVD.setText(lt.getSVD());
           }else{
               MessageDialogHelper.showMessageDialog(parentForm,"Không tìm thấy trận đấu có mã trận theo yêu cầu","Thông báo");
           }
       } catch (Exception e) {
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");
       }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnTaomoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaomoiActionPerformed
    txtMatran.setText("");
    txtTran.setText("");
    txtNgay.setText("");
    txtGio.setText("");
    txtSVD.setText("");
    }//GEN-LAST:event_btnTaomoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
       StringBuilder sb = new StringBuilder();
       DataValidator.validateEmpty(txtMatran, sb,"Mã trận không được để trống");
       DataValidator.validateEmpty(txtTran, sb, "Trận đấu không được để trống");
       if(sb.length()>0){
           MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
           return;
       }
        try {
           Lichthidau lt = new Lichthidau();
           lt.setMatran(txtMatran.getText());
           lt.setTrandau(txtTran.getText());
           lt.setNgay(txtNgay.getText());
           lt.setGio(txtGio.getText());
           lt.setSVD(txtSVD.getText());
           
           LichThiDauDao dao = new LichThiDauDao();
           if(dao.findByMaTran(txtMatran.getText()) != null){
               if(MessageDialogHelper.showConfirmDialog(parentForm, 
                       "Bạn có muốn cập nhật Trận đấu không ?","Hỏi")==JOptionPane.NO_OPTION){
                   return;
               }
               if(dao.update(lt)){
                   MessageDialogHelper.showMessageDialog(parentForm,"Trận đấu đã được cập nhật","Thông báo");
               }else{
                   MessageDialogHelper.showMessageDialog(parentForm,"Không thể cập nhật trận đấu","Thông báo");
               }
           }else{
               if(dao.insert(lt)){
                 MessageDialogHelper.showMessageDialog(parentForm, "Trận đấu đã được lưu","Thông báo");
                 loadDataToTable();
               }else{
                 MessageDialogHelper.showConfirmDialog(parentForm, "Trận đấu chưa được lưu do lỗi","Thông báo");
           }
               loadDataToTable();
           }
       } catch (Exception e) {
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(parentForm,
                   e.getMessage(),"Lỗi");
       }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
       StringBuilder sb = new StringBuilder();
       DataValidator.validateEmpty(txtMatran, sb,"Mã trận không được để trống");
       if(sb.length()>0){
           MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
           return;
       }
       if (MessageDialogHelper.showConfirmDialog(parentForm, 
               "Bạn có muốn cập nhật trận đấu không ?", "Hỏi") == JOptionPane.NO_OPTION){
           return;
       }
        try {
           Lichthidau lt = new Lichthidau();
           lt.setMatran(txtMatran.getText());
           lt.setTrandau(txtTran.getText());
           lt.setNgay(txtNgay.getText());
           lt.setGio(txtGio.getText());
           lt.setSVD(txtSVD.getText());

           LichThiDauDao dao = new LichThiDauDao();
           if(dao.update(lt)){
               MessageDialogHelper.showMessageDialog(parentForm, "Trận đấu đã được cập nhật","Thông báo");
               loadDataToTable();
           }else{
               MessageDialogHelper.showConfirmDialog(parentForm, "Trận đấu không được cập nhật do lỗi","Cảnh báo");
           }
           loadDataToTable();
       } catch (Exception e) {
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(parentForm,
                   e.getMessage(),"Lỗi");
       }
    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       StringBuilder sb = new StringBuilder();
       DataValidator.validateEmpty(txtMatran, sb,"Mã trận không được để trống");
       if(sb.length()>0){
           MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
           return;
       }
       if (MessageDialogHelper.showConfirmDialog(parentForm, 
               "Bạn có muốn xoá trận đấu  không ?", "Hỏi") == JOptionPane.NO_OPTION){
           return;
       }
        try {
           LichThiDauDao dao = new LichThiDauDao();
           if(dao.deleteByMaTran(txtMatran.getText())){
               MessageDialogHelper.showMessageDialog(parentForm, "Trận đấu đã được xoá","Thông báo");
               btnTaomoiActionPerformed(evt);
               loadDataToTable();
           }else{
               MessageDialogHelper.showConfirmDialog(parentForm, "Trận đấu không được xoá do lỗi","Cảnh báo");
           }
           loadDataToTable();
       } catch (Exception e) {
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(parentForm,
                   e.getMessage(),"Lỗi");
       } 
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCalendarMouseClicked
       try {
           int row = tblCalendar.getSelectedRow();
           
           if(row >= 0){
               String ma = (String) tblCalendar.getValueAt(row, 0);
               LichThiDauDao dao  = new LichThiDauDao();
               Lichthidau lt =dao.findByMaTran(ma);
           
               if(lt != null){
                   txtMatran.setText(lt.getMatran());
                   txtTran.setText(lt.getTrandau());
                   txtNgay.setText(lt.getNgay());
                   txtGio.setText(lt.getGio());
                   txtSVD.setText(lt.getSVD());
                   
               }
          }
       }catch (Exception e){
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");
       }
    }//GEN-LAST:event_tblCalendarMouseClicked

    private void txtMatranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatranFocusLost
        try {
        LichThiDauDao dao = new LichThiDauDao();
        Lichthidau lt = dao.findByMaTran(txtMatran.getText());
        if(lt != null){
            txtTran.setText(lt.getTrandau());
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtMatranFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnTaomoi;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable tblCalendar;
    private javax.swing.JTextField txtGio;
    private javax.swing.JTextField txtMatran;
    private javax.swing.JTextField txtMatranTK;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtSVD;
    private javax.swing.JTextField txtTran;
    // End of variables declaration//GEN-END:variables
}
