/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan_1;

import Helper.SharedData;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class qlct extends javax.swing.JFrame {
   private PlayersManagementPanel mPlayerPanel;
   private ltdManagementPanel mCalendarPanel;
   private ResultManagementPanel mResultPanel;
   
    /**
     * Creates new form qlct
     */
    public qlct() {
        initComponents();
        
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        tblExit = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        tbrQuanLyCauThu = new javax.swing.JButton();
        tbrLichThiDau = new javax.swing.JButton();
        tbrKetQuaThiDau = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        tbrAboutUs = new javax.swing.JButton();
        tplMainBoard = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblLoginName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        mnuFile_Exit = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuResultManage = new javax.swing.JMenu();
        mnuManagePlayers = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuManageCalendar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuManageResult = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnuAboutUs = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        tblExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit (2).png"))); // NOI18N
        tblExit.setText("Thoát");
        tblExit.setFocusable(false);
        tblExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tblExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblExitActionPerformed(evt);
            }
        });
        jToolBar1.add(tblExit);
        jToolBar1.add(jSeparator9);

        tbrQuanLyCauThu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbrQuanLyCauThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/athlete (1).png"))); // NOI18N
        tbrQuanLyCauThu.setText("Quản lý cầu thủ");
        tbrQuanLyCauThu.setFocusable(false);
        tbrQuanLyCauThu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrQuanLyCauThu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrQuanLyCauThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrQuanLyCauThuActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrQuanLyCauThu);

        tbrLichThiDau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbrLichThiDau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calendar (1).png"))); // NOI18N
        tbrLichThiDau.setText("Lịch thi đấu");
        tbrLichThiDau.setFocusable(false);
        tbrLichThiDau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrLichThiDau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrLichThiDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrLichThiDauActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrLichThiDau);

        tbrKetQuaThiDau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbrKetQuaThiDau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/scoreboard (2).png"))); // NOI18N
        tbrKetQuaThiDau.setText("Kết quả thi đấu ");
        tbrKetQuaThiDau.setFocusable(false);
        tbrKetQuaThiDau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrKetQuaThiDau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrKetQuaThiDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrKetQuaThiDauActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrKetQuaThiDau);
        jToolBar1.add(jSeparator10);

        tbrAboutUs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbrAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info (1).png"))); // NOI18N
        tbrAboutUs.setText("Giới thiệu");
        tbrAboutUs.setFocusable(false);
        tbrAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrAboutUs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrAboutUsActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrAboutUs);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));
        jPanel1.add(tplMainBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1200, 460));

        lblLoginName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblLoginName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoginName, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 180, 70));

        jMenu1.setText("Hệ thống");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout (1).png"))); // NOI18N
        jMenuItem1.setText("Đăng xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        mnuFile_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuFile_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        mnuFile_Exit.setText("Thoát");
        mnuFile_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFile_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuFile_Exit);
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        mnuResultManage.setText("Quản lý");
        mnuResultManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuResultManageActionPerformed(evt);
            }
        });

        mnuManagePlayers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuManagePlayers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/athlete.png"))); // NOI18N
        mnuManagePlayers.setText("Quản lý Cầu thủ");
        mnuManagePlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManagePlayersActionPerformed(evt);
            }
        });
        mnuResultManage.add(mnuManagePlayers);
        mnuResultManage.add(jSeparator3);

        mnuManageCalendar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnuManageCalendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calendar.png"))); // NOI18N
        mnuManageCalendar.setText("Lịch thi đấu");
        mnuManageCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageCalendarActionPerformed(evt);
            }
        });
        mnuResultManage.add(mnuManageCalendar);
        mnuResultManage.add(jSeparator4);

        mnuManageResult.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mnuManageResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/scoreboard (1).png"))); // NOI18N
        mnuManageResult.setText("Kết quả thi đấu");
        mnuManageResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageResultActionPerformed(evt);
            }
        });
        mnuResultManage.add(mnuManageResult);
        mnuResultManage.add(jSeparator7);

        jMenuBar1.add(mnuResultManage);

        mnuAboutUs.setText("Trợ giúp");
        mnuAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutUsActionPerformed(evt);
            }
        });

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info.png"))); // NOI18N
        jMenuItem5.setText("Nội Dung");
        mnuAboutUs.add(jMenuItem5);
        mnuAboutUs.add(jSeparator5);

        jMenuBar1.add(mnuAboutUs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuFile_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFile_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuFile_ExitActionPerformed

    private void mnuManageResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageResultActionPerformed
        if(mResultPanel == null){
        mResultPanel = new ResultManagementPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icon/scoreboard (2).png"));
        tplMainBoard.addTab("Kết quả thi đấu", icon,mResultPanel,"Kết quả thi đấu");            
        }
        tplMainBoard.setSelectedComponent(mResultPanel);
    }//GEN-LAST:event_mnuManageResultActionPerformed

    private void tbrQuanLyCauThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrQuanLyCauThuActionPerformed
        if(mPlayerPanel == null){
        mPlayerPanel = new PlayersManagementPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icon/athlete (1).png"));
        tplMainBoard.addTab("Quản lý cầu thủ", icon,mPlayerPanel,"Quản lý cầu thủ");
        }
        tplMainBoard.setSelectedComponent(mPlayerPanel);
    }//GEN-LAST:event_tbrQuanLyCauThuActionPerformed

    private void mnuManagePlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManagePlayersActionPerformed
        // TODO add your handling code here:
        if(mPlayerPanel == null){
        mPlayerPanel = new PlayersManagementPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icon/athlete (1).png"));
        tplMainBoard.addTab("Quản lý cầu thủ", icon,mPlayerPanel,"Quản lý cầu thủ");
        }
        tplMainBoard.setSelectedComponent(mPlayerPanel);
    }//GEN-LAST:event_mnuManagePlayersActionPerformed

    private void tblExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblExitActionPerformed
        setVisible(false);  
    }//GEN-LAST:event_tblExitActionPerformed

    private void mnuManageCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageCalendarActionPerformed
        if(mCalendarPanel == null){
           mCalendarPanel = new ltdManagementPanel(); 
           ImageIcon icon = new ImageIcon(getClass().getResource("/icon/calendar (1).png"));
        tplMainBoard.addTab("Lịch thi đấu", icon,mCalendarPanel,"Lịch thi đấu");
        }
        tplMainBoard.setSelectedComponent(mCalendarPanel);
    }//GEN-LAST:event_mnuManageCalendarActionPerformed

    private void tbrAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrAboutUsActionPerformed
        new AboutUsFrame().setVisible(true);
    }//GEN-LAST:event_tbrAboutUsActionPerformed

    private void mnuAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutUsActionPerformed
        new AboutUsFrame().setVisible(true);        
    }//GEN-LAST:event_mnuAboutUsActionPerformed

    private void mnuResultManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuResultManageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuResultManageActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginDialog().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tbrLichThiDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrLichThiDauActionPerformed
        if(mCalendarPanel == null){
           mCalendarPanel = new ltdManagementPanel(); 
           ImageIcon icon = new ImageIcon(getClass().getResource("/icon/calendar (1).png"));
        tplMainBoard.addTab("Lịch thi đấu", icon,mCalendarPanel,"Lịch thi đấu");
        }
        tplMainBoard.setSelectedComponent(mCalendarPanel);
    }//GEN-LAST:event_tbrLichThiDauActionPerformed

    private void tbrKetQuaThiDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrKetQuaThiDauActionPerformed
        if(mResultPanel == null){
        mResultPanel = new ResultManagementPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icon/scoreboard (2).png"));
        tplMainBoard.addTab("Kết quả thi đấu", icon,mResultPanel,"Kết quả thi đấu");            
        }
        tplMainBoard.setSelectedComponent(mResultPanel);
    }//GEN-LAST:event_tbrKetQuaThiDauActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         new LoginDialog().setVisible(true);
         
    }//GEN-LAST:event_formWindowOpened
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qlct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qlct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qlct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qlct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new qlct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblLoginName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JMenu mnuAboutUs;
    private javax.swing.JMenuItem mnuFile_Exit;
    private javax.swing.JMenuItem mnuManageCalendar;
    private javax.swing.JMenuItem mnuManagePlayers;
    private javax.swing.JMenuItem mnuManageResult;
    private javax.swing.JMenu mnuResultManage;
    private javax.swing.JButton tblExit;
    private javax.swing.JButton tbrAboutUs;
    private javax.swing.JButton tbrKetQuaThiDau;
    private javax.swing.JButton tbrLichThiDau;
    private javax.swing.JButton tbrQuanLyCauThu;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
