/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan_1;

import Dao.KetQuaThiDauDao;
import Entities.Ketquathidau;
import Helper.DataValidator;
import Helper.MessageDialogHelper;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ResultManagementPanel extends javax.swing.JPanel {
private qlct parentForm;
private DefaultTableModel tblModel;
    /**
     * Creates new form ResultManagementPanel
     */
    public ResultManagementPanel() {
        initComponents();
        initTable();
        loadDataToTable();
    }
        private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã trận ","Trận đấu","Ngày","Giờ","Tỉ số"});
        tblResults.setModel(tblModel);
    }
    private void loadDataToTable(){
        try {
            KetQuaThiDauDao dao = new KetQuaThiDauDao();
            List <Ketquathidau> list = dao.findAllKetQuaThiDau();
            tblModel.setRowCount(0);
            for(Ketquathidau kq : list){
                tblModel.addRow(new Object[]{
                   kq.getMaTran(),kq.getTranDau(),kq.getNgay(),kq.getGio(),kq.getTiSo()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMatranTK = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMatran = new javax.swing.JTextField();
        txtTran = new javax.swing.JTextField();
        txtNgay = new javax.swing.JTextField();
        txtGio = new javax.swing.JTextField();
        txtTiso = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnTaomoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResults = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("KẾT QUẢ THI ĐẤU");

        jLabel2.setText("Mã Trận");

        btnTimkiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMatranTK, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnTimkiem)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMatranTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Mã trận");

        jLabel4.setText("Trận");

        jLabel5.setText("Ngày");

        jLabel6.setText("Giờ");

        jLabel7.setText("Tỉ số");

        txtMatran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatranFocusLost(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/scoreboard (3).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMatran)
                    .addComponent(txtTran)
                    .addComponent(txtNgay)
                    .addComponent(txtGio)
                    .addComponent(txtTiso, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMatran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnTaomoi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTaomoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/creation.png"))); // NOI18N
        btnTaomoi.setText("Tạo mới");
        btnTaomoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaomoiActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/diskette.png"))); // NOI18N
        btnLuu.setText("Lưu ");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete (1).png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapnhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCapnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/recycle.png"))); // NOI18N
        btnCapnhat.setText("Cập nhât");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        tblResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã trận", "Trận", "Ngày", "Giờ", "Tỉ số"
            }
        ));
        tblResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnTaomoi)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapnhat)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2))
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaomoi)
                    .addComponent(btnLuu)
                    .addComponent(btnXoa)
                    .addComponent(btnCapnhat))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaomoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaomoiActionPerformed
       txtMatran.setText("");
       txtTran.setText("");
       txtNgay.setText("");
       txtGio.setText("");
       txtTiso.setText("");
    }//GEN-LAST:event_btnTaomoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
       StringBuilder sb = new StringBuilder();
       DataValidator.validateEmpty(txtMatran, sb,"Mã trận không được để trống");
       DataValidator.validateEmpty(txtTran, sb, "Trận đấu không được để trống");
       if(sb.length()>0){
           MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
           return;
       }
        try {
           Ketquathidau kq = new Ketquathidau();
           kq.setMaTran(txtMatran.getText());
           kq.setTranDau(txtTran.getText());
           kq.setNgay(txtNgay.getText());
           kq.setGio(txtGio.getText());
           kq.setTiSo(txtTiso.getText());
           
           KetQuaThiDauDao dao = new KetQuaThiDauDao();
           if(dao.findByMaTran(txtMatran.getText()) != null){
               if(MessageDialogHelper.showConfirmDialog(parentForm, 
                       "Bạn có muốn cập nhật Kết quả thi đấu không ?","Hỏi")==JOptionPane.NO_OPTION){
                   return;
               }
               if(dao.update (kq)){
                   MessageDialogHelper.showMessageDialog(parentForm,"Kết quả thi đấu đã được cập nhật","Thông báo");
               }else{
                   MessageDialogHelper.showMessageDialog(parentForm,"Không thể cập nhật kết quả thi đấu","Thông báo");
               }
           }else{
               if(dao.insert(kq)){
                 MessageDialogHelper.showMessageDialog(parentForm, "Kết quả thi đấu đã được lưu","Thông báo");
                 loadDataToTable();
               }else{
                 MessageDialogHelper.showConfirmDialog(parentForm, "Kết quả thi đấu chưa được lưu do lỗi","Thông báo");
           }
               loadDataToTable();
           }
       } catch (Exception e) {
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(parentForm,
                   e.getMessage(),"Lỗi");
       }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
       StringBuilder sb = new StringBuilder();
       DataValidator.validateEmpty(txtMatran, sb,"Mã trận không được để trống");
       if(sb.length()>0){
           MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
           return;
       }
       if (MessageDialogHelper.showConfirmDialog(parentForm, 
               "Bạn có muốn cập nhật Kết quả thi đấu không ?", "Hỏi") == JOptionPane.NO_OPTION){
           return;
       }
        try {
           Ketquathidau lt = new Ketquathidau();
           lt.setMaTran(txtMatran.getText());
           lt.setTranDau(txtTran.getText());
           lt.setNgay(txtNgay.getText());
           lt.setGio(txtGio.getText());
           lt.setTiSo(txtTiso.getText());

           KetQuaThiDauDao dao = new KetQuaThiDauDao();
           if(dao.update(lt)){
               MessageDialogHelper.showMessageDialog(parentForm, "Kết quả thi đấu đã được cập nhật","Thông báo");
               loadDataToTable();
           }else{
               MessageDialogHelper.showConfirmDialog(parentForm, "Kết quả thi đấu không được cập nhật do lỗi","Cảnh báo");
           }
           loadDataToTable();
       } catch (Exception e) {
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(parentForm,
                   e.getMessage(),"Lỗi");
       }
    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    try {
        if(txtMatran.getText().equals("")){
            MessageDialogHelper.showMessageDialog(parentForm,"Mã trận cần phải nhập" ,"Lỗi");
            return;
        }
        
        KetQuaThiDauDao dao = new KetQuaThiDauDao();
        Ketquathidau kq = dao.findByMaTran(txtMatran.getText());
        if(kq == null){
            MessageDialogHelper.showMessageDialog(parentForm,"Mã trận không tồn tại trong bảng","Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn xoá trận đấu không ?","Hỏi")
                == JOptionPane.NO_OPTION){
            return;
        }
        if(dao.deleteByMaTran(txtMatran.getText())){
            MessageDialogHelper.showMessageDialog(parentForm,"Trận đấu đã được xoá","Thông báo");
        }else{
            MessageDialogHelper.showMessageDialog(parentForm,"Trận đấu chưa thể xoá","Thông báo");
        }
        loadDataToTable();
    } catch (Exception e) {
        e.printStackTrace();
        MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultsMouseClicked
       try {
           int row = tblResults.getSelectedRow();
           
           if(row >= 0){
               String ma = (String) tblResults.getValueAt(row, 0);
               KetQuaThiDauDao dao  = new KetQuaThiDauDao();
               Ketquathidau lt =dao.findByMaTran(ma);
           
               if(lt != null){
                   txtMatran.setText(lt.getMaTran());
                   txtTran.setText(lt.getTranDau());
                   txtNgay.setText(lt.getNgay());
                   txtGio.setText(lt.getGio());
                   txtTiso.setText(lt.getTiSo());
                   
               }
          }
       }catch (Exception e){
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");
       }
    }//GEN-LAST:event_tblResultsMouseClicked

    private void txtMatranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatranFocusLost
        try {
        KetQuaThiDauDao dao = new KetQuaThiDauDao();
        Ketquathidau kq = dao.findByMaTran(txtMatran.getText());
        if(kq != null){
            txtTran.setText(kq.getTranDau());
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtMatranFocusLost

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
       try {
           KetQuaThiDauDao dao = new KetQuaThiDauDao();
           Ketquathidau kq = dao.findByMaTran(txtMatranTK.getText());
           
           if(kq != null){
              txtMatran.setText(kq.getMaTran());
              txtTran.setText(kq.getTranDau());
              txtNgay.setText(kq.getNgay());
              txtGio.setText(kq.getGio());
              txtTiso.setText(kq.getTiSo());
           }else{
               MessageDialogHelper.showMessageDialog(parentForm,"Không tìm thấy trận đấu có mã trận theo yêu cầu","Thông báo");
           }
       } catch (Exception e) {
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");
       }
    }//GEN-LAST:event_btnTimkiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnTaomoi;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblResults;
    private javax.swing.JTextField txtGio;
    private javax.swing.JTextField txtMatran;
    private javax.swing.JTextField txtMatranTK;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtTiso;
    private javax.swing.JTextField txtTran;
    // End of variables declaration//GEN-END:variables
}
